version: '3'
services:
  crf-pos:
    image: "mforouhesh/crf-pos:2.2.3"
    container_name: crf-pos
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /usr/app/resources
      - .:/user/app
    ports:
      - "5000:5000"
    command: ["sh", "startup.sh"]