version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
  test:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - run:
          name: Run tests
          command: |
            pip install pytest
            pytest -v      
  coverage:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - run:
          name: Run coverage
          command: |
            coverage run main.py
            coverage report -m
  lint:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - checkout
      - run:
          name: Install Dependancies 
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install flake8 flake8-commas flake8-comprehensions flake8-tidy-imports
      - run:
          name: Lint with flake8
          command: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

workflows:
  build_test_coverage:
    jobs:
      - build:
          context: org-global
      - test:
          requires:
            - build
          context: org-global
      - coverage:
          requires:
            - build
            - test
          context: org-global
            