version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
  test:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - run:
          name: Run tests
          command: |
            pip install pytest
            pytest -v      
  coverage:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - run:
          name: Run coverage
          command: |
            coverage run main.py
            coverage report -m

workflows:
  build_test_coverage_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
            - test
            