version: 2.1

orbs:
  python: circleci/python@1.5.0
executors:
  installation:
    docker:
      - image: cimg/python:3.7.12
    working_directory: /tmp
          
jobs:
  build:
    executor: installation
    steps:
      - checkout
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - /*
      - python/install-packages:
          pkg-manager: pip
      - run: ls -a
          
  test:
    executor: installation
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pytest -v
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

  coverage:
    executor: installation
    steps:
      - checkout
      - run:
          name: Run coverage
          command: |
            coverage run main.py
            coverage report -m
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
          
  lint:
    docker:
      - image: cimg/python:3.7.12
    steps:
      - checkout
      - run:
          name: Install Dependancies 
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install flake8 flake8-commas flake8-comprehensions flake8-tidy-imports
      - run:
          name: Lint with flake8
          command: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

workflows:
  build_test_coverage:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
            - test
            